dec/urls.py
from django.contrib import admin
from django.urls import path, include
from websites.views import HomeView, ItemDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView
from websites.views import add_to_cart, remove_from_cart, OrderSummaryView, remove_single_item_from_cart 
from websites.views import CheckoutView, Payment
admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', HomeView.as_view(), name="home" ),    
    path('add_to_cart/<int:pk>/', add_to_cart, name="add_to_cart"),
    path('remove_single_item_from_cart/<int:pk>/', remove_single_item_from_cart, name="remove_single_item_from_cart"),
    path('order-summary/', OrderSummaryView.as_view(), name="order-summary"),
    path('remove_from_cart/<int:pk>/', remove_from_cart, name="remove_from_cart"),
    path('product/create/', ProductCreateView.as_view(), name="create"),
    path('product/<int:pk>/', ItemDetailView.as_view(), name="product"),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name="update"),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name="delete"),
    path('checkoutview/', CheckoutView.as_view(), name="checkout"),
    path('payment/<payment_option>/', Payment.as_view(), name="payment"),
    
]

websites/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone
from django.db.models.signals import post_save
from django.urls import reverse
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


category_choices = (
    ("S", "Shirt"),
    ("SW", "SportsWear"),
    ("O", "Outwear"),
)

label_choices = (
    ("P", "Primary"),
    ("S", "Secondary"),
    ("D", "Danger"),
)

ADDRESS_CHOICES = (
    ("P", "Paypal"),
    ("S", "Stripe"),
    
)



class Item(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=250)    
    label = models.CharField(choices=label_choices, max_length=2, blank=True, null=True)
    category = models.CharField(choices=category_choices, max_length=2, blank=True, null=True)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    #image = models.ImageField()
    slug = models.SlugField()  
    

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("product", kwargs={'pk': self.pk})

    def get_add_to_cart_url(self):
        return reverse("add_to_cart", kwargs={'pk': self.pk}) 

    def get_remove_from_cart_url(self):
        return reverse("remove_from_cart", kwargs={'pk': self.pk})


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)

    def get_total(self):
        return self.quantity * self.item.price

    def get_discount_total(self):
        return self.quantity * self.item.discount_price

    


class Order(models.Model):
    items = models.ManyToManyField(OrderItem)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    billing_address = models.ForeignKey(
        "Address", related_name="billing_address", on_delete=models.SET_NULL, blank=True, null=True)
    shipping_address = models.ForeignKey(
        "Address", related_name="shipping_address", on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        "Payment", on_delete=models.SET_NULL, blank=True, null=True)




class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


    def get_total1(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total()        
        return total

def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address =  models.CharField(max_length=100)                        
    apartment_address = models.CharField(max_length=100)
    countries = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)
    

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    stripe_charge_id = models.CharField(max_length=50)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Material Design Bootstrap</title>
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }
  </style>
</head>
{% include 'navbar.html' %}
<body>
  <div style="height: 100px;">

  </div>
  

</body>

</html>

{% include 'messages.html' %}

{% block content %}
{% endblock content %}
{% block extra_body %}
{% endblock %}

{% include 'footer.html' %}

templates/checkout-page.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<main>
  <div class="container wow fadeIn">
    <h2 class="my-5 h2 text-center">Checkout form</h2>
    <div class="row">
      <div class="col-md-8 mb-4">
        <div class="card">
          <form method="POST" class="card-body">
            {% csrf_token %}

            <h3>Shipping address</h3>

            <div class='hideable_shipping_form'>

              <div class="md-form mb-5">
                <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address'
                  class='form-control' />
                <label for="shipping_address" class="">Address</label>
              </div>

              <div class="md-form mb-5">
                <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2'
                  class='form-control' />
                <label for="shipping_address2" class="">Address 2 (optional)</label>
              </div>

              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  {{ form.billing_country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="shipping_zip">Zip</label>
                  <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip'
                    class='form-control' />
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>
                </div>
              </div>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="same_billing_address"
                  id="same_billing_address">
                <label class="custom-control-label" for="same_billing_address">Billing address is the same as my
                  shipping address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="set_default_shipping"
                  id="set_default_shipping">
                <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
              </div>

            </div>

            {% if default_shipping_address %}
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
              <label class="custom-control-label" for="use_default_shipping">Use default shipping address:
                {{ default_shipping_address.street_address|truncatechars:10 }}</label>
            </div>
            {% endif %}

            <hr>

            <h3>Billing address</h3>

            <div class='hideable_billing_form'>
              <div class="md-form mb-5">
                <input type='text' placeholder='1234 Main St' id='billing_address' name='billing_address'
                  class='form-control' />
                <label for="billing_address" class="">Address</label>
              </div>

              <div class="md-form mb-5">
                <input type='text' placeholder='Apartment or suite' id='billing_address2' name='billing_address2'
                  class='form-control' />
                <label for="billing_address2" class="">Address 2 (optional)</label>
              </div>

              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  {{ form.billing_country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>

                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="billing_zip">Zip</label>
                  <input type='text' placeholder='Zip code' id='billing_zip' name='billing_zip' class='form-control' />
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>
                </div>

              </div>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing">
                <label class="custom-control-label" for="set_default_billing">Save as default billing address</label>
              </div>

            </div>

            {% if default_billing_address %}
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing">
              <label class="custom-control-label" for="use_default_billing">Use default billing address:
                {{ default_billing_address.street_address|truncatechars:10 }}</label>
            </div>
            {% endif %}
            <hr>

            <h3>Payment option</h3>

            <div class="d-block my-3">
              {% for value, name in form.fields.payment_option.choices %}
              <div class="custom-control custom-radio">
                <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio"
                  class="custom-control-input" required>
                <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
              </div>
              {% endfor %}
            </div>

            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

          </form>

        </div>

      </div>

      <div class="col-md-4 mb-4">
        
      </div>

    </div>

  </div>
</main>

{% endblock content %}

{% block extra_scripts %}
<script>
  var hideable_shipping_form = $('.hideable_shipping_form');
  var hideable_billing_form = $('.hideable_billing_form');

  var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
  var use_default_billing = document.querySelector("input[name=use_default_billing]");

  use_default_shipping.addEventListener('change', function () {
    if (this.checked) {
      hideable_shipping_form.hide();
    } else {
      hideable_shipping_form.show();
    }
  })

  use_default_billing.addEventListener('change', function () {
    if (this.checked) {
      hideable_billing_form.hide();
    } else {
      hideable_billing_form.show();
    }
  })

</script>
{% endblock extra_scripts %}

templates/footer.html
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

  <!--Call to action-->
  <div class="pt-4">
    <a class="btn btn-outline-white" href="https://mdbootstrap.com/docs/jquery/getting-started/download/"
      target="_blank" role="button">Download MDB
      <i class="fas fa-download ml-2"></i>
    </a>
    <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank"
      role="button">Start
      free tutorial
      <i class="fas fa-graduation-cap ml-2"></i>
    </a>
  </div>
  <!--/.Call to action-->

  <hr class="my-4">

  <!-- Social icons -->
  <div class="pb-4">
    <a href="https://www.facebook.com/mdbootstrap" target="_blank">
      <i class="fab fa-facebook-f mr-3"></i>
    </a>

    <a href="https://twitter.com/MDBootstrap" target="_blank">
      <i class="fab fa-twitter mr-3"></i>
    </a>

    <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
      <i class="fab fa-youtube mr-3"></i>
    </a>

    <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
      <i class="fab fa-google-plus-g mr-3"></i>
    </a>

    <a href="https://dribbble.com/mdbootstrap" target="_blank">
      <i class="fab fa-dribbble mr-3"></i>
    </a>

    <a href="https://pinterest.com/mdbootstrap" target="_blank">
      <i class="fab fa-pinterest mr-3"></i>
    </a>

    <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
      <i class="fab fa-github mr-3"></i>
    </a>

    <a href="http://codepen.io/mdbootstrap/" target="_blank">
      <i class="fab fa-codepen mr-3"></i>
    </a>
  </div>
  <!-- Social icons -->

  <!--Copyright-->
  <div class="footer-copyright py-3">
    © 2019 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
  </div>
  <!--/.Copyright-->

</footer>
<!--/.Footer-->

templates/home-page.html
{% extends 'base.html' %}


{% block content %}

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">

          {% for item in object_list %} 
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"
                  alt="">
                <a href="{% url 'product' item.id %}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="{% url 'product' item.id %}" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill danger-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h5 class="font-weight-bold blue-text">
                  
                  <strong>${{ item.discount_price }}</strong>
                  
                  <del><strong>${{ item.price }}</strong></del>
                  
                </h5>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->

      {% endfor %}

         

      

    </div>
  </main>
  <!--Main layout-->

<!--Pagination-->


<div class="container">
  <div class="row text-center">
    <div class="col-12">

      {% if is_paginated %}
        {% if page_obj.has_previous %}
          <a class="btn btn-sm btn-cyan" href="?page=1">First</a>
          <a class="btn btn-sm btn-cyan" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
          {% if num == page_obj.number %}
            <a class="btn btn-sm btn-blue-grey" href="?page={{ num }}">{{ num }}</a>
          {% elif num > page_obj.number|add:"-2" and num < page_obj.number|add:"2" %}
            <a class="btn btn-sm btn-blue-grey" href="?page={{ num }}">{{ num }}</a>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <a class="btn btn-sm btn-cyan" href="?page={{ page_obj.next_page_number }}">Next</a>
          <a class="btn btn-sm btn-cyan" href="?page={{ page_obj.paginator.num_pages }}">Last</a>          
        {% endif %}

      {% endif %}









    </div>
  </div>
</div>


{% endblock content %}

templates/item_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}

<div class="container-fluid mt-5">
  <div class="row text-center">
    <div class="col-12 text-center">
      <form action="" method="post">
        <div>
          {% csrf_token %}
          {{ form|crispy }}
        </div>
        <button class="btn btn-lg btn-success" type="submit"><strong>Post</strong></button>
      </form>



    </div>



  </div>

</div>

{% endblock %}

templates/messages.html
  <div class="row">
    {% if messages %}
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 alert-success text-center p-2">      
        {% for message in messages %}
          {{ message }}
        {% endfor %}
    {% endif %}
    </div>
  </div>

templates/navbar.html
{% load cart_template_tags %}


<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container">
    {% if user.is_authenticated %}
    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="{% url 'home' %}" target="_blank">
      <strong class="blue-text">CHFashion</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link waves-effect" href="{% url 'home' %}">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>                
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        <li class="nav-item">
          <a href="{% url 'order-summary' %}" class="nav-link waves-effect">
            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'account_logout' %}" class="nav-link waves-effect" target="_blank">Logout
            
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'account_logout' %}" class="nav-link waves-effect" target="_blank">Profile
        
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a href="{% url 'account_login' %}" class="nav-link waves-effect" target="_blank">Login
        
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'account_signup' %}" class="nav-link waves-effect" target="_blank">Sign-up
        
          </a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a href="{% url 'account_email' %}" class="nav-link waves-effect" target="_blank">Change E-mail
        
          </a>
        </li>
        
        
      </ul>

    </div>

  </div>
</nav>
<!-- Navbar -->

templates/product-page.html
{% extends 'base.html' %}
{% block content %}
  

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">New</span>
              </a>
              <a href="">
                <span class="badge red mr-1">{{ object.get_label_display }}</span>
              </a>
            </div>

            <p class="lead">
              <span class="mr-1">
              {% if object.discount_price %}
                <del class="mr-2">${{ object.price }}</del>
                ${{ object.discount_price }}
              </span>
              {% else %}
              <span>${{ object.discount_price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

            <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <a href="{{ object.get_add_to_cart_url}}" class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>              
              <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p" type="submit">Remove from cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>

            </form>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Other Products</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/scripts.html
<!-- SCRIPTS -->
<!-- JQuery -->
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>